// SPDX-License-Identifier: MPL-2.0

//! The durable lower-source identity record (`P1-07`).
//!
//! This module owns the stateless `trusted.overlay.origin` record end-to-end
//! (encode / persist / decode / read): [`LowerIdRecord`] is a pure value type
//! carrying the pre-copy-up provenance pair `(fsid, real_ino)` of the lower
//! source, the module-private `ORIGIN_*` consts freeze the native 24-byte wire
//! layout (Linux `struct ovl_fb` design root, NOT Linux-wire-compatible — no
//! export-style FH exists in Asterinas), and the two [`OverlayFs`] seam
//! methods (`store_lower_id` / `read_lower_id`) bridge the record to the upper
//! inode's xattr surface.
//!
//! The record has **no runtime owner** (user-directed topology amendment
//! 2026-08-02): it is generated by meso-04's copy-up publication via
//! [`OverlayFs::store_lower_id`] and consumed by this Meso's `IdentityPolicy`
//! via [`OverlayFs::read_lower_id`]; the xattr value is the single durable
//! source of the lower identity and encode/decode are pure value transforms.
//! The two seam methods are hosted here because they need only the mount
//! policy (capability gate) and the upper real inode, not the caches; they
//! hold no Overlay lock (the record appears in no lock-carrier row).

use super::entry::RealObject;
use crate::{
    fs::{
        fs_impls::overlayfs::mount::OverlayFs,
        vfs::{
            inode::Inode,
            xattr::{XattrName, XattrSetFlags},
        },
    },
    prelude::*,
};

/// The durable lower-source identity record (`P1-07`).
///
/// A stateless value type: it carries the lower layer `fsid` and the real
/// inode number of the lower source (pre-copy-up provenance) and never
/// crosses the `overlayfs` layer. The xattr value written via
/// [`OverlayFs::store_lower_id`] is the single durable source of the lower
/// identity; encode/decode are pure value transforms.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(super) struct LowerIdRecord {
    /// Lower layer fsid (meso-01 published); the layer id for the xino mask
    /// (`P2-01`).
    fsid: u64,
    /// Real inode number of the lower source (pre-copy-up provenance).
    real_ino: u64,
}

/// The full name of the origin xattr (Linux `OVL_XATTR_ORIGIN` design root;
/// module-private per the packet).
///
/// The value is the native 24-byte wire buffer produced by
/// [`LowerIdRecord::serialize`] — the layout is not Linux-wire-compatible
/// because no export-style file handle exists in Asterinas. The const full
/// name is design-validated (`trusted.` namespace).
const ORIGIN_XATTR_FULL_NAME: &str = "trusted.overlay.origin";

/// Wire version; a larger version on the wire means "origin unknown"
/// (`Ok(None)`).
const ORIGIN_WIRE_VERSION: u8 = 1;

/// The "fb" wire magic (Linux `OVL_FH_MAGIC` design root).
const ORIGIN_WIRE_MAGIC: u32 = 0x0000_00fb;

/// Wire header length: magic (4) + version/flags/type (4).
const ORIGIN_WIRE_HEADER_LEN: usize = 8;

/// Wire payload length: `fsid: u64` + `real_ino: u64`, native endian.
const ORIGIN_WIRE_PAYLOAD_LEN: usize = 16;

/// Total native wire length (24 bytes).
const ORIGIN_WIRE_TOTAL_LEN: usize = ORIGIN_WIRE_HEADER_LEN + ORIGIN_WIRE_PAYLOAD_LEN;

/// The only known flag bits; any unknown flag bits mean "origin unknown"
/// (`Ok(None)`).
const ORIGIN_WIRE_FLAGS_KNOWN: u8 = 0;

impl LowerIdRecord {
    /// Constructs the record from a lower [`RealObject`].
    ///
    /// Returns `Ok(Some(record))` from the lower's published `fsid` and real
    /// inode number — both infallible fields, so the native record is always
    /// constructible this wave. `Ok(None)` is reserved for the absent
    /// export-FH seam (unreachable), and `Err` is reserved for genuine source
    /// failures (none expected).
    #[expect(
        dead_code,
        reason = "frozen P1-07 constructor (spec revision 07); consumed by the deferred `OverlayFs::store_lower_id` seam once meso-04 lands"
    )]
    pub(super) fn try_from_lower(lower: &RealObject) -> Result<Option<Self>> {
        Ok(Some(Self {
            fsid: lower.fsid(),
            real_ino: lower.real_inode().ino(),
        }))
    }

    /// Serializes the record into the native 24-byte wire buffer.
    ///
    /// Header layout: `magic` (4 bytes) + `version`/`flags`/`type`/reserved
    /// (4 bytes); payload: `fsid`/`real_ino` (16 bytes), all native endian.
    /// The wire "type" byte is zero this wave — the record is a native
    /// identity pair, not an export-style file handle.
    #[expect(
        dead_code,
        reason = "frozen P1-07 wire encoder (spec revision 07); consumed by the deferred `OverlayFs::store_lower_id` seam once meso-04 lands"
    )]
    pub(super) fn serialize(&self) -> Vec<u8> {
        let mut wire = Vec::with_capacity(ORIGIN_WIRE_TOTAL_LEN);
        wire.extend_from_slice(&ORIGIN_WIRE_MAGIC.to_ne_bytes());
        wire.push(ORIGIN_WIRE_VERSION);
        wire.push(ORIGIN_WIRE_FLAGS_KNOWN);
        wire.push(0); // wire type: native identity record (no export-style FH)
        wire.push(0); // reserved header byte
        wire.extend_from_slice(&self.fsid.to_ne_bytes());
        wire.extend_from_slice(&self.real_ino.to_ne_bytes());
        wire
    }

    /// Conservatively decodes a wire buffer into a record.
    ///
    /// Returns `Ok(None)` on any structural mismatch — zero-size or wrong
    /// length, magic, version, or unknown flag bits (Linux `ovl_check_fb_len`
    /// semantics). `Err` is reserved and unreachable in the pure decode this
    /// wave (retained for the frozen signature).
    pub(super) fn decode(bytes: &[u8]) -> Result<Option<Self>> {
        if bytes.len() != ORIGIN_WIRE_TOTAL_LEN {
            return Ok(None);
        }
        let magic = u32::from_ne_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
        if magic != ORIGIN_WIRE_MAGIC {
            return Ok(None);
        }
        if bytes[4] != ORIGIN_WIRE_VERSION {
            return Ok(None);
        }
        if (bytes[5] & !ORIGIN_WIRE_FLAGS_KNOWN) != 0 {
            return Ok(None);
        }
        let fsid = u64::from_ne_bytes([
            bytes[8], bytes[9], bytes[10], bytes[11], bytes[12], bytes[13], bytes[14], bytes[15],
        ]);
        let real_ino = u64::from_ne_bytes([
            bytes[16], bytes[17], bytes[18], bytes[19], bytes[20], bytes[21], bytes[22], bytes[23],
        ]);
        Ok(Some(Self { fsid, real_ino }))
    }

    /// Returns the lower layer `fsid`.
    pub(super) fn fsid(&self) -> u64 {
        self.fsid
    }

    /// Returns the real inode number of the lower source.
    pub(super) fn real_ino(&self) -> u64 {
        self.real_ino
    }
}

impl OverlayFs {
    /// Persists the lower-source identity record on the upper inode (`P1-07`
    /// store seam).
    ///
    /// Capability gate — returns `Ok(())` with NO record, never silently
    /// wrong, when the upper capabilities are absent, the upper cannot store
    /// private overlay xattrs, or the backend rejects the write with
    /// `EOPNOTSUPP`; other errors propagate. The record is persisted with
    /// exactly one `set_xattr(..., CREATE_OR_REPLACE)` call under the frozen
    /// `trusted.overlay.origin` full name, so a store is never partially
    /// written. The unreachable `try_from_lower` `None` arm maps defensively
    /// to `EINVAL` (never `.unwrap()`, priors §2). Ordering: meso-04 invokes
    /// this seam before its facts replacement (caller obligation, frozen by
    /// the meso-04 revision-02 packet).
    #[expect(
        dead_code,
        reason = "frozen P1-07 store seam (spec revision 07); consumed by meso-04 `publish_upper_authority` once it lands"
    )]
    pub(super) fn store_lower_id(&self, upper: &Arc<dyn Inode>, lower: &RealObject) -> Result<()> {
        let Some(capabilities) = self.policy().upper_capabilities() else {
            return Ok(());
        };
        if !capabilities.can_store_private_xattr() {
            return Ok(());
        }
        let Some(record) = LowerIdRecord::try_from_lower(lower)? else {
            return Err(Error::with_message(
                Errno::EINVAL,
                "the lower-id record is not constructible",
            ));
        };
        let name = XattrName::try_from_full_name(ORIGIN_XATTR_FULL_NAME).ok_or_else(|| {
            Error::with_message(Errno::EINVAL, "invalid overlay origin xattr name")
        })?;
        let value = record.serialize();
        let mut reader = VmReader::from(&value).to_fallible();
        match upper.set_xattr(name, &mut reader, XattrSetFlags::CREATE_OR_REPLACE) {
            // Runtime `EOPNOTSUPP` is a gated no-op: `Ok(())` with no record,
            // never silently wrong.
            Err(err) if err.error() == Errno::EOPNOTSUPP => Ok(()),
            result => result,
        }
    }

    /// Reads the persisted lower-source identity record from the upper inode
    /// (`P1-07` read seam).
    ///
    /// Returns `Ok(None)` (no record) when the upper answers `ENODATA` or
    /// `EOPNOTSUPP`, the value is zero-size or has a non-canonical length, the
    /// conservative [`LowerIdRecord::decode`] rejects the value, OR the
    /// record's `fsid` does not denote a LOWER layer of the current mount
    /// (wave-2 review item 5, `validate-at-boundaries`): `fsid` is a per-mount
    /// ordinal assigned by `OverlayLayerStack::assemble`, so a record
    /// persisted by an earlier mount with a different layer stack — or
    /// shipped inside an untrusted layer image — must never be projected;
    /// unknown/foreign fsids read as "no record" and keep the visible-source
    /// fallback in `project_inode` (never silently wrong, never
    /// identity-colliding). Genuine xattr-read errors propagate. Consumed by
    /// `IdentityPolicy` via `project_inode` and by meso-04's re-projection.
    pub(super) fn read_lower_id(&self, upper: &Arc<dyn Inode>) -> Result<Option<LowerIdRecord>> {
        let name = XattrName::try_from_full_name(ORIGIN_XATTR_FULL_NAME).ok_or_else(|| {
            Error::with_message(Errno::EINVAL, "invalid overlay origin xattr name")
        })?;
        let mut value = [0u8; ORIGIN_WIRE_TOTAL_LEN];
        let mut writer = VmWriter::from(&mut value).to_fallible();
        match upper.get_xattr(name, &mut writer) {
            Ok(written) => {
                let Some(record) = LowerIdRecord::decode(&value[..written])? else {
                    return Ok(None);
                };
                // Layer validation at the read boundary (wave-2 review item
                // 5): the origin record is written at copy-up from a LOWER
                // source, so only a current LOWER-layer fsid may be trusted.
                // A record never legitimately carries the upper's own fsid.
                let is_current_lower_layer = self
                    .lower_layer_fsids()
                    .any(|lower_fsid| lower_fsid == record.fsid());
                Ok(is_current_lower_layer.then_some(record))
            }
            Err(err) if err.error() == Errno::ENODATA => Ok(None),
            Err(err) if err.error() == Errno::EOPNOTSUPP => Ok(None),
            Err(err) => Err(err),
        }
    }
}
